
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb config_rs/192.168.176.242:10001,192.168.176.242:10002,192.168.176.242:10003 --bind_ip_all
    ports:
      - 30000:27017
    networks:
      - db_network

networks:
  db_network:
    external: true
