
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb config_rs/<your_ip>:10001,<your_ip>:10002,<your_ip>:10003 --bind_ip_all
    ports:
      - 30000:27017
    networks:
      - db_network

networks:
  db_network:
    external: true
